name: Cargar DBF a Firebase Firestore

on:
  workflow_dispatch:        # ejecución manual
  push:
    paths:
      - etl_firestore.py    # corre sólo si cambias este archivo

jobs:
  sync-dbf:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install dbfread google-api-python-client google-auth \
                     google-auth-httplib2 google-auth-oauthlib \
                     firebase-admin python-dateutil

      - name: Ejecutar script etl_firestore.py
        env:
          DRIVE_KEY: ${{ secrets.DRIVE_KEY }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python etl_firestore.py
