name: DBF ➜ Supabase nightly sync

on:
  schedule:
    - cron: "0 */3 * * *"   # cada 3 h (UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: |
          pip install dbfread psycopg[binary] \
                     google-api-python-client google-auth \
                     google-auth-httplib2 google-auth-oauthlib

      # si todavía necesitas la llave de Drive
      - name: Restore Drive key
        run: echo "$DRIVE_KEY" > drive_key.json
        env:
          DRIVE_KEY: ${{ secrets.DRIVE_KEY }}

      - name: Run ETL script
        env:
          SUPA_DSN:  ${{ secrets.SUPA_DSN }}   # ← nombre correcto
          DRIVE_KEY: ${{ secrets.DRIVE_KEY }}  # si la usas dentro de etl.py
        run: python etl.py
